-- JOB_TITLE
INSERT INTO JOB_TITLE VALUES(1, 'Mason');
INSERT INTO JOB_TITLE VALUES(2, 'Carpenter');

-- HEADHUNTER
INSERT INTO HEADHUNTER VALUES(1, 'James');
INSERT INTO HEADHUNTER VALUES(2, 'Mark');

-- CANDIDATE
INSERT INTO CANDIDATE VALUES(1, 'Virat');
INSERT INTO CANDIDATE VALUES(2, 'Rohith');