-- JOB_TITLE
INSERT INTO JOB_TITLE VALUES(1, 'Mason');
INSERT INTO JOB_TITLE VALUES(2, 'Carpenter');

-- HEAD_HUNTER
INSERT INTO HEAD_HUNTER VALUES(1, 'James');
INSERT INTO HEAD_HUNTER VALUES(2, 'Mark');
